name: RMP
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
    - pytorch=1.10.0=py3.7_cuda11.3_cudnn8.2.0_0
    - pytorch-mutex=1.0=cuda
    - torchaudio=0.10.0=py37_cu113
    - torchvision=0.11.1=py37_cu113
    - pip:
        - h5py==3.7.0
        - matplotlib==3.5.2
        - matplotlib-inline==0.1.3
        - numpy==1.19.5
        - pandas==1.3.5
        - pyproj==3.2.1
        - pyquaternion==0.9.9
        - scipy==1.7.3
        - pyyaml==6.0
        - easydict==1.10
        - wandb==0.15.0
        - pyparsing==3.0.9
        - opencv-python==4.5.5.64
